# Generated by Django 4.1.7 on 2023-03-19 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название проекта", max_length=255, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Описание проекта", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата создания проекта"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название спринта", max_length=255, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Описание спринта", null=True
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Дата начала спринта", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Дата окончания спринта", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата создания проекта"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Проект",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sprints",
                        to="task_manager_app.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Наименование статуса", max_length=32, unique=True
                    ),
                ),
                (
                    "rang_status",
                    models.IntegerField(help_text="Очередь статуса", unique=True),
                ),
            ],
            options={
                "ordering": ["rang_status"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название задачи", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Описание задачи", null=True
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата создания задачи"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, help_text="Дата обновления задачи"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, help_text="Дата начала", null=True),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, help_text="Дата окончания", null=True),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Назначено напользователя",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Проект задачи",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_task",
                        to="task_manager_app.project",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        blank=True,
                        help_text="Спринт",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sprint_task",
                        to="task_manager_app.sprint",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        default="Создана",
                        help_text="Статус задачи",
                        max_length=20,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_task",
                        to="task_manager_app.status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["created_date"],
            },
        ),
        migrations.CreateModel(
            name="TaskHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_task_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_task_history",
                        to="task_manager_app.status",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_history",
                        to="task_manager_app.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата создания уведомления"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пользователь",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Задача",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_task",
                        to="task_manager_app.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalTask",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Название задачи", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Описание задачи", null=True
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Дата создания задачи"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Дата обновления задачи"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, help_text="Дата начала", null=True),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, help_text="Дата окончания", null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Назначено напользователя",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Проект задачи",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="task_manager_app.project",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Спринт",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="task_manager_app.sprint",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default="Создана",
                        help_text="Статус задачи",
                        max_length=20,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="task_manager_app.status",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Task",
                "verbose_name_plural": "historical Tasks",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
